alter table _countries
  drop title_be,
  drop title_cz,
  drop title_de,
  drop title_en,
  drop title_es,
  drop title_fr,
  drop title_it,
  drop title_ja,
  drop title_lt,
  drop title_lv,
  drop title_pl,
  drop title_pt,
  drop title_ua,
  change country_id id bigint primary key auto_increment,
  change title_ru title varchar(150) not null,
  add index country_title (title);

alter table _regions
  drop title_be,
  drop title_cz,
  drop title_de,
  drop title_en,
  drop title_es,
  drop title_fr,
  drop title_it,
  drop title_ja,
  drop title_lt,
  drop title_lv,
  drop title_pl,
  drop title_pt,
  drop title_ua,
  change region_id id bigint primary key auto_increment,
  change title_ru title varchar(150) not null,
  modify country_id bigint not null,
  add index region_title (title),
  add foreign key (country_id) references _countries (id);

alter table _cities
  drop area_be,
  drop title_be,
  drop region_be,
  drop area_cz,
  drop title_cz,
  drop region_cz,
  drop area_de,
  drop title_de,
  drop region_de,
  drop area_en,
  drop title_en,
  drop region_en,
  drop area_es,
  drop title_es,
  drop region_es,
  drop area_fr,
  drop title_fr,
  drop region_fr,
  drop area_ja,
  drop title_ja,
  drop region_ja,
  drop area_it,
  drop title_it,
  drop region_it,
  drop area_lt,
  drop title_lt,
  drop region_lt,
  drop area_lv,
  drop title_lv,
  drop region_lv,
  drop area_pl,
  drop title_pl,
  drop region_pl,
  drop area_pt,
  drop title_pt,
  drop region_pt,
  drop area_ru,
  drop region_ru,
  drop area_ua,
  drop title_ua,
  drop region_ua,
  change city_id id bigint primary key auto_increment,
  modify country_id bigint not null,
  modify region_id bigint not null,
  change title_ru title varchar(150) not null,
  add index title_region (title),
  add foreign key (country_id) references _countries (id),
  add foreign key (region_id) references _regions (id);
delete
from _cities
where region_id is null;
